version: '3'

services:
  matcher:
    container_name: matcher
    build: .
    volumes:
      - '.:/csh' # HOST:CONTAINER
    ports:
      - 5001:5000 # HOST:CONTAINER
    environment:
      - S3_BUCKET=dsapp-criminal-justice
      - INDEXER=identity
      - KEYS=["first_name","last_name"]
      - CONTRASTER=exact

  db:
    container_name: csh_db
    image: postgres:10
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=csh
      - POSTGRES_PASSWORD=csh
      - POSTGRES_DB=csh
