version: '3'

services:
  matcher:
    container_name: matcher
    build: .
    volumes:
      - '.:/csh'
    ports:
      - 5001:5000 # HOST:CONTAINER
    environment:
      - S3_BUCKET=dsapp_criminal_justice/csh/matcher
      - INDEXER=identity
      - KEYS=["first_name","last_name"]
      - CONTRASTER=exact

  db:
    container_name: csh_db
    image: postgres:10
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=csh
      - POSTGRES_PASSWORD=csh
      - POSTGRES_DB=csh
