site_name: Matching Tool
docs_dir: sources
repo_name: Github
repo_url: https://github.com/dssg/matching-tool/
theme: material
markdown_extensions:
    - toc:
        permalink: True
        baselevel: 2
pages:
    - {Home: index.md}
    - For Users:
        - {Using the Tool: users/using.md}
        - Schemas:
            - {Booking AKA/Alias Schema: users/schemas/booking-akaalias-data.md}
            - {Booking Charge Schema: users/schemas/booking-charging-data.md}
            - {Booking Schema: users/schemas/booking-data.md}
            - {By-Name Schema: users/schemas/by-name-list.md}
            - {Case Charge Schema: users/schemas/case-charge-data.md}
            - {Homelessness Services AKA/Alias Schema: users/schemas/hmis-akaalias-data.md}
            - {Homelessness Service Stays Schema: users/schemas/hmis-data.md}
    - For Administrators:
        - {Installing: admin/install.md}
        - {Troubleshooting: admin/troubleshooting.md}
        - {Updating: admin/updating.md}
        - {Configuring the Matching Service: admin/matching.md}
    - For Developers:
        - {Getting Started: dev/getting-started.md}
        - {Creating or Modifying a Schema: dev/schemas.md}
        - {Modifying the Webapp: dev/webapp.md}
        - {Modifying the Matching Service: dev/matching.md}
